---
kind: Service
apiVersion: v1
metadata:
    name: infiria-demo
spec:
    selector:
        app: infiria-demo-webapp
    ports:
        - name: web
          protocol: TCP
          port: 4200
          targetPort: 4200
---
kind: Service
apiVersion: v1
metadata:
    name: infiria-demo-api
spec:
    selector:
        app: infiria-demo-api
    ports:
        - name: web
          protocol: TCP
          port: 3000
          targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: infiria-demo-api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: infiria-demo-api
    template:
        metadata:
            labels:
                app: infiria-demo-api
        spec:
            containers:
                - name: infiria-demo-api
                  image: ghcr.io/ever-co/infiria-api-demo:latest
                  env:
                      - name: API_HOST
                        value: 0.0.0.0
                      - name: DEMO
                        value: 'true'
                      - name: NODE_ENV
                        value: 'development'
                      - name: ADMIN_PASSWORD_RESET
                        value: 'true'
                      - name: LOG_LEVEL
                        value: 'info'
                      - name: SENTRY_DSN
                        value: 'https://7cd381188b6f446ca0e69185227b9031@o51327.ingest.sentry.io/4397292'
                      - name: SENTRY_HTTP_TRACING_ENABLED
                        value: '$SENTRY_HTTP_TRACING_ENABLED'
                      - name: SENTRY_PROFILING_ENABLED
                        value: '$SENTRY_PROFILING_ENABLED'
                      - name: SENTRY_POSTGRES_TRACKING_ENABLED
                        value: '$SENTRY_POSTGRES_TRACKING_ENABLED'
                      - name: API_BASE_URL
                        value: 'https://apidemocivo.infiria.co'
                      - name: CLIENT_BASE_URL
                        value: 'https://democivo.infiria.co'
                      - name: EXPRESS_SESSION_SECRET
                        value: 'infiria'
                      - name: JWT_SECRET
                        value: 'secretKey'
                      - name: JWT_REFRESH_TOKEN_SECRET
                        value: 'refreshSecretKey'
                      - name: JWT_REFRESH_TOKEN_EXPIRATION_TIME
                        value: '86400'
                      - name: CLOUD_PROVIDER
                        value: '$CLOUD_PROVIDER'
                      - name: OTEL_ENABLED
                        value: '$OTEL_ENABLED'
                      - name: OTEL_PROVIDER
                        value: '$OTEL_PROVIDER'
                      - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
                        value: '$OTEL_EXPORTER_OTLP_TRACES_ENDPOINT'
                      - name: OTEL_EXPORTER_OTLP_HEADERS
                        value: '$OTEL_EXPORTER_OTLP_HEADERS'
                  ports:
                      - containerPort: 3000
                        protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: infiria-demo-webapp
spec:
    replicas: 1
    selector:
        matchLabels:
            app: infiria-demo-webapp
    template:
        metadata:
            labels:
                app: infiria-demo-webapp
        spec:
            containers:
                - name: infiria-demo-webapp
                  image: ghcr.io/ever-co/infiria-webapp-demo:latest
                  env:
                      - name: DEMO
                        value: 'true'
                      - name: API_BASE_URL
                        value: 'https://apidemocivo.infiria.co'
                      - name: CLIENT_BASE_URL
                        value: 'https://democivo.infiria.co'
                      - name: SENTRY_DSN
                        value: 'https://7cd381188b6f446ca0e69185227b9031@o51327.ingest.sentry.io/4397292'
                      - name: CHATWOOT_SDK_TOKEN
                        value: 'jFoSXEjGmqhUhqU3zfgkFfMt'
                      - name: CLOUDINARY_API_KEY
                        value: '256868982483961'
                      - name: CLOUDINARY_CLOUD_NAME
                        value: 'dv6ezkfxg'
                      - name: GOOGLE_MAPS_API_KEY
                        value: 'AIzaSyCJmnKzgTSq5Pc93HXar5bZrdmANTwtSIo'
                      - name: GOOGLE_PLACE_AUTOCOMPLETE
                        value: 'true'
                      - name: DEFAULT_LATITUDE
                        value: '42.6459136'
                      - name: DEFAULT_LONGITUDE
                        value: '23.3332736'
                      - name: DEFAULT_CURRENCY
                        value: 'USD'
                      - name: INFIRIA_GITHUB_CLIENT_ID
                        value: '$INFIRIA_GITHUB_CLIENT_ID'
                      - name: INFIRIA_GITHUB_APP_NAME
                        value: '$INFIRIA_GITHUB_APP_NAME'
                      - name: INFIRIA_GITHUB_REDIRECT_URL
                        value: '$INFIRIA_GITHUB_REDIRECT_URL'
                      - name: INFIRIA_GITHUB_POST_INSTALL_URL
                        value: '$INFIRIA_GITHUB_POST_INSTALL_URL'
                      - name: INFIRIA_GITHUB_APP_ID
                        value: '$INFIRIA_GITHUB_APP_ID'
                      - name: JITSU_BROWSER_URL
                        value: '$JITSU_BROWSER_URL'
                      - name: JITSU_BROWSER_WRITE_KEY
                        value: '$JITSU_BROWSER_WRITE_KEY'
                  ports:
                      - containerPort: 4200
                        protocol: TCP
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
    name: https-redirect
spec:
    redirectScheme:
        permanent: true
        scheme: https
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: infiria-demo
    namespace: default
    annotations:
        kubernetes.io/ingress.class: traefik
spec:
    rules:
        - host: democivo.infiria.co
          http:
              paths:
                  - backend:
                        service:
                            name: infiria-demo
                            port:
                                number: 4200
                    path: /
                    pathType: Prefix
    tls:
        - hosts:
              - democivo.infiria.co
          secretName: democivo.infiria.co-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: infiria-demo-api
    namespace: default
    annotations:
        kubernetes.io/ingress.class: traefik
spec:
    rules:
        - host: apidemocivo.infiria.co
          http:
              paths:
                  - backend:
                        service:
                            name: infiria-demo-api
                            port:
                                number: 3000
                    path: /
                    pathType: Prefix
    tls:
        - hosts:
              - apidemocivo.infiria.co
          secretName: apidemocivo.infiria.co-tls
